### ISSUE TITLE
Parents field missing in Group By

### ISSUE THREAD

**Issue by Massimo-B** [trac-hacks/trac-subtickets-plugin#18]
In Ticket queries there is no parents field in the listbox of GroupBy.
However using it in the macro like  `[[TicketQuery(group=parents,format=list)]] `works fine.

**Comment by thenor57** [comment]
That is because the Parent field data type is 'text', which again is because a child may have more than one parent. If you add other text-type custom fields, you'll see them have the same behaviour.

Workaround: Don't use the custom query functionality. Switch to SQL and use the stored functions supplied with the plugin. Here is a query that may be what you want:
```
SELECT 
    r.id, summary, 
    milestone,
    status,
    CASE WHEN r.parent IS NULL 
       THEN 'font-weight:bolder;background-color:lightgrey'
       ELSE 'text-indent: ' ||10*level||'px' 
    END AS __style__
FROM 
    tracsubticket_tree() r 
JOIN 
    ticket t ON r.id=t.id 
WHERE
    t.id IS NOT NULL
    AND level <= 2
ORDER by path
```

Instead of using the stored function, you may be able to include it directly in the query. However, I haven't experimented with that and in any case the query will be much more difficult to read.

HTH

**Comment by Massimo-B** [comment]
I found out that it perfectly works by just adding the `group=parents` to the URL or to the [[TicketQuery]] macro. So actually the listbox of grouping could just offer those text fields as well.

**Comment by thenor57** [comment]
Interesting! Possibly a candidate for an enhancement ticket to Trac?

In any case, I'll add these quirks to the plugin documentation. Thanks.
