### ISSUE TITLE
Traceback while auto-previewing a new ticket if a parent ticket doesn't exist

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/trac-subtickets-plugin#20]
The following traceback can be seen in the console if a non-existent parent ticket is added to a newticket and the page is allowed to auto-preview. If the preview button is pressed, then the user is redirected to `/newticket#ticket` and an error message is displayed.

```
09:05:43 PM Trac[api] ERROR: Ticket 5 does not exist.
09:05:43 PM Trac[main] ERROR: Exception caught while post-processing request: 
Traceback (most recent call last):
  File "/home/user/Workspace/stp6/trac-trunk/trac/web/main.py", line 243, in dispatch
    self._post_process_request(req)
  File "/home/user/Workspace/stp6/trac-trunk/trac/web/main.py", line 340, in _post_process_request
    f.post_process_request(req, *(None,)*extra_arg_count)
  File "build/bdist.linux-i686/egg/tracsubtickets/web_ui.py", line 65, in post_process_request
    ticket = data['ticket']
TypeError: 'NoneType' object is unsubscriptable
09:05:43 PM Trac[main] WARNING: [127.0.0.1] HTTPNotFound: 404 Invalid ticket number (Ticket 5 does not exist.)
127.0.0.1 - - [21/Oct/2012 21:05:43] "POST /tracdev/newticket HTTP/1.1" 404 -
```

The desirable behavior would be to show a warning message at the top of the page when `Preview` is pressed. If some fixes are applied in `validate_ticket`, then it should function this way.

(Moved from https://github.com/itota/trac-subtickets-plugin/issues/27)

**Comment by rjollos** [comment]
Looks like I may have tried to fix in my fork, but it was some time ago so I don't remember: https://github.com/rjollos/trac-subtickets-plugin/commit/f7e4683bf5de4355a24d8ced383d101afeaf2f39

**Comment by thenor57** [comment]
I need a little help in understanding the validation process:

When auto-previewing, _every_ `Yield()`ed error condition found by `api.validate_ticket()` goes unreported on the UI while they are nicely reported when pressing `Preview`. I can see no  difference in plugin behaviour. Why? Is it an inherent behaviour of Trac?

The behaviour is the same for `newticket` and for updates of existing tickets.

I see in all cases that `api.validate_ticket`() is called first, followed by `web_ui.validate_ticket()`. In all cases, if `api-validate_ticket()` `Yield()`s, `parents` is set to `None` before `web_ui.validate_ticket()` is called.

The second question is: The split of validation between `web_ui` and `api` is inherited from @itota, the intention probably being to keep all SQL inside a single module. It seems that the validation done in `api` ought to be called directly from `web_ui` rather than via the extension point mechanism. Or?

**Comment by rjollos** [comment]
I will have to do some investigation. I hope to get back to you soon.

**Comment by rjollos** [comment]
There's no validation done during auto-preview. Doing so could be quite annoying - consider the case of validating the summary to be non-empty. If you start by filling out the description you would see a warning as soon as you pause typing long enough to trigger an auto-preview.

I would combine the `ITicketManipulator` implementations in `web_ui.py` like you suggested. If you want to keep the SQL in `api.py` just call methods on `SubTicketsSystem` from within `validate_ticket`.

**Comment by rjollos** [comment]
I can't reproduce this issue with Trac 1.0-stable or 1.2-stable. The invalid ticket ID is removed on preview and submit.
